services:
  - type: web
    name: buscador-empresas-mar
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_API_KEY_3
        sync: false
      - key: GROQ_API_KEY_4
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
